<?php
require_once("AddressController.php");
require_once("nationalityController.php");
require_once("relationController.php");
require_once("MaritalController.php");
require_once("ChildtypeController.php");
require_once("StatusController.php");
require_once("pageController.php");
require_once("WeekController.php");
require_once("usertypeluController.php");
require_once("utl_intController.php");
require_once("attend_intController.php");
require_once("qualificationController.php");
require_once("ChildtypeController.php");
require_once("CoursesController.php");
require_once("scheduleController.php");
require_once("eventsController.php");
require_once("BranchController.php");
require_once("MonthController.php");
require_once("PaymentController.php");
require_once("OptionController.php");
 ?>
